# Generated by Django 3.2.1 on 2021-05-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210505_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
