# Generated by Django 3.2.1 on 2021-05-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_companyinformation_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinformation',
            old_name='logo',
            new_name='Logo',
        ),
    ]
