# Generated by Django 3.2.1 on 2021-05-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_companyinformation_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mrcreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Mr_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Class', models.CharField(blank=True, max_length=100, null=True)),
                ('Doc_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Date', models.CharField(blank=True, max_length=255, null=True)),
                ('Insured_Name', models.CharField(blank=True, max_length=1500, null=True)),
                ('Insured_Address', models.CharField(blank=True, max_length=1500, null=True)),
                ('Bank_Name', models.CharField(blank=True, max_length=1500, null=True)),
                ('Bank_Address', models.CharField(blank=True, max_length=1500, null=True)),
                ('Premium', models.CharField(blank=True, max_length=255, null=True)),
                ('Vat', models.CharField(blank=True, max_length=255, null=True)),
                ('Stamp', models.CharField(blank=True, max_length=255, null=True)),
                ('ServiceCharge', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('Mode_Of_Payment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
