# Generated by Django 3.2.1 on 2021-05-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_mrcreate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mrcreate',
            old_name='Date',
            new_name='Mr_Date',
        ),
    ]
