# Generated by Django 3.2.1 on 2021-05-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_date_mrcreate_mr_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrcreate',
            name='Mr_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
