# Generated by Django 3.2.1 on 2021-05-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_mrcreate_mr_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mrcreate',
            old_name='Mr_Date',
            new_name='Date',
        ),
    ]
