# Generated by Django 3.2.1 on 2021-05-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_rename_mr_date_mrcreate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='Bin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
