# Generated by Django 3.2.1 on 2021-05-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_companyinformation_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrcreate',
            name='Total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
