# Generated by Django 3.2.1 on 2021-05-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_mrcreate_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrcreate',
            name='Total_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
