# Generated by Django 3.2.1 on 2021-05-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_mrcreate_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrcreate',
            name='inword',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
